name: Build

on:
    push:
        tags:
            - "v*.*.*"

env:
    APP_NAME: ProfitProphet
    BINARY_NAME: pprophet

permissions:
    contents: write

jobs:
    build:
        name: Building

        strategy:
            matrix:
                include:
                    - os: macos-latest
                      arch: arm64
                    - os: ubuntu-latest
                      arch: x64
                    - os: windows-latest
                      arch: x64

        runs-on: ${{ matrix.os }}

        steps:
            - name: Doing checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Setting up Python
              uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
              with:
                  python-version: 3.14
                  architecture: ${{ matrix.arch }}

            - name: Installing dependencies
              run: |
                  pip install uv
                  uv export --no-dev -o requirements.txt
                  pip install -r requirements.txt

            - name: Compiling
              uses: Nuitka/Nuitka-Action@0d4e22d4b66062a13d120f6948dd90170be04b3a # v1.4
              with:
                  script-name: src
                  mode: onefile
                  python-flag: -m

            - name: Preparing binary
              shell: bash
              run: |
                  mkdir -p dist
                  mkdir -p dist.unpacked

                  VERSION="${GITHUB_REF_NAME#v}"
                  OS="$(echo '${{ runner.os }}' | tr '[:upper:]' '[:lower:]')"
                  ARCH="${{ matrix.arch }}"

                  if [ "${{ runner.os }}" = "Windows" ]; then
                    cp "build/src.exe" "dist.unpacked/${BINARY_NAME}.exe"
                    powershell.exe -Command "
                    Compress-Archive -Path dist.unpacked\* \
                      -DestinationPath dist\${env:APP_NAME}-${VERSION}-${OS}-${ARCH}.zip \
                      -Force
                    "
                  else
                    cp "build/src.bin" "dist.unpacked/${BINARY_NAME}"
                    tar -czf "dist/${APP_NAME}-${VERSION}-${OS}-${ARCH}.tar.gz" dist.unpacked/*
                  fi

            - name: Uploading artifacts
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: ${{ env.APP_NAME }}-${{ runner.os }}-${{ matrix.arch }}
                  path: dist/*

    release:
        name: Release
        needs: build

        runs-on: ubuntu-latest

        steps:
            - name: Downloading artifacts
              uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
              with:
                  path: dist

            - name: Creating release
              uses: softprops/action-gh-release@2bb465e97f322d3cb2a965294d483e0d26a67aa9 # v3.0.1
              with:
                  files: dist/**/*
                  make_latest: true
                  generate_release_notes: true
